modLoader="javafml"
loaderVersion="[45,)"
license="MIT License"

[[mods]]
modId="stellartech"
version="1.0.0"
displayName="StellarTech"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://github.com/niceFilms/StellarTech"
authors="niceFilms"

[[dependencies.stellartech]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




